#!/bin/bash
sdb 'db=new Sdb("localhost",11810,"sdbadmin","sdbadmin")'

sdb 'db.getRG("group1").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group2").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group3").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group4").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group5").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group6").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group7").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group8").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group9").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group10").reelect({HostName:"jsdb01"})'
sdb 'db.getRG("group11").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group12").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group13").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group14").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group15").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group16").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group17").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group18").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group19").reelect({HostName:"jsdb02"})'
sdb 'db.getRG("group20").reelect({HostName:"jsdb02"})'

sdb 'db.getRG("group21").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group22").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group23").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group24").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group25").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group26").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group27").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group28").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group29").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group30").reelect({HostName:"jsdb03"})'
sdb 'db.getRG("group31").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group32").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group33").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group34").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group35").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group36").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group37").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group38").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group39").reelect({HostName:"jsdb04"})'
sdb 'db.getRG("group40").reelect({HostName:"jsdb04"})'

sdb 'db.getRG("group41").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group42").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group43").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group44").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group45").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group46").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group47").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group48").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group49").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group50").reelect({HostName:"jsdb05"})'
sdb 'db.getRG("group51").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group52").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group53").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group54").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group55").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group56").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group57").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group58").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group59").reelect({HostName:"jsdb06"})'
sdb 'db.getRG("group60").reelect({HostName:"jsdb06"})'

sdb 'db.snapshot(12,{IsPrimary:true},{NodeName:""})'
